Debug jinja render functionality
innolitics/n2y pull request #105
Opened 2023-02-19 22:44 UTC by sHermanGriffiths

# Author's Checklist

Before assigning reviewers, step through the following checklist. Check each item once it's completed. If an item is skipped, write an explanation below the item.

- [ ] **Construction:** Review the code diff and confirm there's no dead code, debug code, or unnecessary comments.
- [ ] **Requirements:** Review the requirements in the issue for this PR and confirm they're all implemented.
- [ ] **Architecture:** Confirm that the changes to the code are consistent with the existing architecture.
- [ ] **SOUP/OTS Software:** Any new dependencies have appropriate licenses and are documented or pinned in requirements files.
- [ ] **Unit Test:** Atomic unit tests have been added, if appropriate.
- [ ] **End-to-End Tests:** End-to-end tests have been extended or updated, if appropriate.
- [ ] **Low-level Documentation:** Comments or doc strings for affected code have been updated.
- [ ] **High-Level Documentation:** The README is updated, as appropriate.
- [ ] **Change Log:** New features or bug fixes have been added to the change log in the README.

2023-02-20 18:17 UTC, johndgiese commented on n2y/plugins/hiddenjinjatoggles.py
>  class HiddenJinjaToggleBlock(ToggleBlock):
Can you rename this to "ExpandBlueToggleBlock". Also can you rename the file to "expandbluetoggles.py"

2023-02-21 21:54 UTC, bimbashrestha requested changes

2023-02-21 21:54 UTC, bimbashrestha commented on n2y/plugins/expandbluetoggles.py
> +        if self.notion_type_data["color"] != "blue_background":
We'll need to update the test for this as well: [tests/test_hiddenjinjatoggles.py](https://github.com/innolitics/n2y/pull/102/files#diff-6fd060877e313b38e5a31293414cd3517041c4b9bdb406eefe42c3e20501ddb5)

2023-02-21 21:54 UTC, bimbashrestha commented on n2y/plugins/jinjarenderpage.py
> +        parent_id = self.notion_parent['database_id'].replace('-', '')
Use https://github.com/innolitics/n2y/blob/main/n2y/utils.py#L136-L138 please

2023-02-21 21:54 UTC, bimbashrestha commented on n2y/notion.py
> +            retry_after = 'retry-after' in err.headers
This variable naming is a bit confusing to me. `retry_after` is a boolean but we also later use it as the amount to sleep by. Maybe we can just use two variables here: one as the boolean to see if we have `retry-after` in the headers and one that stores the amount to sleep by?

2023-02-23 16:24 UTC, bimbashrestha commented
Changes look good! Just get CI passing and this is good to go

2023-02-23 18:10 UTC, bimbashrestha approved these changes
Nice work!

2023-02-23 18:11 UTC, merged